FROM centos:latest

COPY container/docker/github/install-centos-packages.sh .
RUN ./install-centos-packages.sh && rm install-centos-packages.sh

WORKDIR /julea
COPY scripts/ ./scripts/ 

SHELL ["/bin/bash", "-c"]
RUN ./scripts/install-dependencies.sh
