#!/bin/sh

# JULEA - Flexible storage framework
# Copyright (C) 2017 Michael Kuhn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

get_directory ()
{
	local directory

	directory="$1"

	test -n "${directory}" || return 1

	printf '%s' "$(readlink --canonicalize-existing -- "${directory}")"
}

set_glib_options ()
{
	export G_SLICE=all
}

set_path ()
{
	local build_dir
	local root_dir

	build_dir="$(get_directory "${SELF_DIR}/../build")"
	root_dir="$(get_directory "${SELF_DIR}/..")"

	export PATH="${build_dir}/benchmark:${build_dir}/server:${build_dir}/test:${build_dir}/tools:${root_dir}/external/mongo-c-driver/bin:${root_dir}/scripts:${PATH}"
}

set_library_path ()
{
	local build_dir
	local root_dir

	build_dir="$(get_directory "${SELF_DIR}/../build")"
	root_dir="$(get_directory "${SELF_DIR}/..")"

	export LD_LIBRARY_PATH="${build_dir}/lib:${root_dir}/external/mongo-c-driver/lib:${LD_LIBRARY_PATH}"
}

set_pkg_config_path ()
{
	local build_dir
	local root_dir

	build_dir="$(get_directory "${SELF_DIR}/../build")"
	root_dir="$(get_directory "${SELF_DIR}/..")"

	export PKG_CONFIG_PATH="${build_dir}/pkg-config:${root_dir}/external/mongo-c-driver/lib:${PKG_CONFIG_PATH}"
}
