#!/usr/bin/env /Rscript

suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))


first_round <- TRUE
last_frame <- NA

# test if all records of the same backend kind (object,kv,db)
# have executed the same order of commands
test_validity <- function(data) {
  res <- TRUE
  data <- subset(
    data,
    select = -c(time, process_uid, program_name, bson, duration)) # nolint: object_usage_linter, line_length_linter.
  for (x in  unique(data$backend)) {
    first_round <<- TRUE
    check <- function(frame, key) {
      if (res == FALSE) {
        return()
      }
      frame <- frame %>% subset(select = -c(backend)) # nolint: object_usage_linter, line_length_linter.
      if (first_round != TRUE) {
        if (nrow(frame) != nrow(last_frame)) {
          res <<- FALSE
         } else if (!Reduce(f = "&", x = frame == last_frame)) {
          res <<- FALSE
        }
      }
      first_round <<- FALSE
      last_frame <<- frame
    }
    data %>% filter(backend == x) %>% group_by(type, path) %>% group_walk(check) # nolint: object_usage_linter, line_length_linter.
  }
  return(res)
}


args <- commandArgs(trailingOnly = TRUE)
print(args)
if (length(args) < 1) {
  stop(
    paste(
      "usage:",
      "script", # TODO check if script name can be determined
      "<summary.csv> <- generated by decission-support.sh"),
    call. = FALSE)
}

data <- read.csv(args[1])

res <- test_validity(data)
if (res == FALSE) {
  stop(
    "Access reports between different configurations are not consistent!",
    call. = FALSE)
}


