# JULEA - Flexible storage framework
# Copyright (C) 2021-2026 Michael Kuhn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Dependencies
on:
  schedule:
    - cron: '0 0 * * 0'
defaults:
  run:
    shell: bash
jobs:
  dependencies:
    name: Dependencies (Containers)
    runs-on: ubuntu-24.04
    container: ${{ matrix.os.registry }}/${{ matrix.os.image }}
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        os:
          - image: ubuntu:24.04-base
            registry: ghcr.io/parcio/julea
            compiler: gcc
            compiler_spack: gcc
            compiler_version: 13.3.0
          - image: ubuntu:24.04-base
            registry: ghcr.io/parcio/julea
            compiler: clang
            compiler_spack: llvm
            compiler_version: 18.1.3
    env:
      JULEA_SPACK_COMPILER: ${{ matrix.os.compiler_spack }}@${{ matrix.os.compiler_version }}
      JULEA_SPACK_DIR: /julea-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          show-progress: false
      - name: Cache dependencies
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.JULEA_SPACK_DIR }}
          key: ${{ matrix.os.image }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
      - name: Install dependencies
        run: |
          rm --recursive --force /julea-dependencies
          ./scripts/install-dependencies.sh
